# Generated by Django 5.1.3 on 2024-11-28 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("targets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="target",
            name="identifier",
        ),
    ]
